#cloud-config

packages:
    - curl
    - jq

write_files:
    - path: /opt/cloud-management-init.sh
      permissions: '0755'
      owner: root:root
      content: |
        #!/bin/bash
        set -euo pipefail

        LOG_FILE="/var/log/cloud-management-init.log"
        exec > >(tee -a "$LOG_FILE") 2>&1
        set -x

        USER_NAME="mjs"; # pick a username you won’t hate tomorrow

        REPO="mjst-internals/cloud-management";
        DESTINATION="cloud-management.tar.gz";

        echo "Downloading latest release...";
        latest=$(curl -s "https://api.github.com/repos/${REPO}/tags" | jq -r '.[0].name');
        curl -L "https://github.com/${REPO}/archive/refs/tags/${latest}.tar.gz" -o "${DESTINATION}";

        echo "Extracting scripts...";
        mkdir -p /opt/cloud-management
        tar -xzf "${DESTINATION}" -C /opt/cloud-management --strip-components=1 --wildcards "cloud-management-*/scripts/bash/";

        echo "Setting permissions...";
        chmod +x /opt/cloud-management/scripts/bash/*

        echo "Running init script...";
        bash /opt/cloud-management/scripts/bash/init.sh --user "${USER_NAME}";

runcmd:
    - /opt/cloud-management-init.sh

